export const IMAGES = {
  logo: "/images/proavia-logo-light.webp",
  logoDark: "/images/proavia-logo-dark.webp",
  logoPng: "/images/proavia-logo-light.png",
  logoDarkPng: "/images/proavia-logo-dark.png",
  icon: "/images/icon.webp",
  attaLogo: "/images/atta-logo.webp",
  nipdbLogo: "/images/nipdb-logo.webp",
  ntbLogo: "/images/ntb-logo.webp",
  destinations: {
    sandwichHarbourOceanView: "/images/destinations/destination-sandwich-harbour-ocean-view.webp",
    sandwichHarbourCoastalDunes: "/images/destinations/destination-sandwich-harbour-coastal-dunes.webp",
    sandwichHarbourSuvDrive: "/images/destinations/destination-sandwich-harbour-suv-drive.webp",
    sandwichHarbourDuneClimb: "/images/destinations/destination-sandwich-harbour-dune-climb.webp",
    sandwichHarbourSunsetPicnic: "/images/destinations/destination-sandwich-harbour-sunset-picnic.webp",
    walvisBaySaltShore: "/images/destinations/destination-walvis-bay-salt-shore.webp",
    walvisBaySaltPans: "/images/destinations/destination-walvis-bay-salt-pans-crystals.webp",
    walvisBayPinkLake: "/images/destinations/destination-walvis-bay-pink-lake.webp",
    namibDesertPinkSeating: "/images/destinations/destination-namib-desert-pink-seating.webp",
  },
  vehicles: {
    // Replaced weak/old fleet photos with clean real photography (no ProAvia branding on these — only genuine user-supplied photos may carry branding).
    transferFleet: "/images/vehicles/vw-tiguan-transfer-fleet.webp",
    carHireFleet: "/images/vehicles/vw-polo-car-hire-fleet.webp",
    shuttleFleet: "/images/vehicles/toyota-quantum-shuttle-fleet.webp",
    volkswagenSossusvlei: "/images/vehicles/fleet-volkswagen-in-sosslvei.webp",
    volkswagenVehicle: "/images/vehicles/fleet-volskwagen-vehicle.webp",
  },
  experiences: {
    safariElephant: "/images/experiences/proavia-tour-safari-elephant.webp",
    pinkLake: "/images/experiences/proavia-tour-pink-lake-experience.webp",
    marineCatamaran: "/images/experiences/proavia-tour-marine-catamaran.webp",
    desertSuv: "/images/experiences/proavia-tour-desert-suv.webp",
    safariGiraffe: "/images/experiences/proavia-tour-safari-giraffe.webp",
    wildlifeElephantZebras: "/images/experiences/proavia-tour-wildlife-elephant-zebras.webp",
    adventureParagliding: "/images/experiences/proavia-tour-adventure-paragliding.webp",
    desertHeadstand: "/images/experiences/proavia-tour-desert-headstand-fun.webp",
    duneTopFlag: "/images/experiences/experience-dune-top-namibia-flag.webp",
    sandboarding: "/images/experiences/experience-sandboarding-beach.webp",
    portCruiseNight: "/images/experiences/proavia-port-cruise-ship-night.webp",
    duneTracks: "/images/experiences/experience-4x4-dune-tracks.webp",
    pelicanBoat: "/images/experiences/experience-pelican-boat-tour.webp",
    // New client images
    clientDeadvleiWomanWhiteDress: "/images/experiences/client-deadvlei-woman-white-dress.webp",
    clientCapeFurSealsColony: "/images/experiences/client-cape-fur-seals-colony.webp",
    clientSossusvleiDuneRidgeGroup: "/images/experiences/client-sossusvlei-dune-ridge-group.webp",
    clientEtoshaElephantZebraWaterhole: "/images/experiences/client-etosha-elephant-zebra-waterhole.webp",
    clientDeadvleiWomanHatWide: "/images/experiences/client-deadvlei-woman-hat-wide.webp",
    clientSandwichHarbourWomanDunesOcean: "/images/experiences/client-sandwich-harbour-woman-dunes-ocean.webp",
    clientSandwichHarbourManOverlook: "/images/experiences/client-sandwich-harbour-man-overlook.webp",
    clientSpitzkoppeRockArchMan: "/images/experiences/client-spitzkoppe-rock-arch-man.webp",
    clientPinkLakeManHat: "/images/experiences/client-pink-lake-man-hat.webp",
    clientSandwichHarbourDunesAerial: "/images/experiences/client-sandwich-harbour-dunes-aerial.webp",
    clientSpitzkoppeSunsetManSitting: "/images/experiences/client-spitzkoppe-sunset-man-sitting.webp",
    clientSossusvleiDuneTwoMen: "/images/experiences/client-sossusvlei-dune-two-men.webp",
    clientSkeletonCoastShipwreck: "/images/experiences/client-skeleton-coast-shipwreck.webp",
    clientSandboardingWomanStanding: "/images/experiences/client-sandboarding-woman-standing.webp",
    clientFatBikeDunesGroup: "/images/experiences/client-fat-bike-dunes-group.webp",
    clientDesertDinnerSunsetWomen: "/images/experiences/client-desert-dinner-sunset-women.webp",
    clientLodgeFirepitSunset: "/images/experiences/client-lodge-firepit-sunset.webp",
    clientLodgeSundownerDeck: "/images/experiences/client-lodge-sundowner-deck.webp",
    clientHotAirBalloonNamib: "/images/experiences/client-hot-air-balloon-namib.webp",
    clientMoonValleySunsetGroup: "/images/experiences/client-moon-valley-sunset-group.webp",
    clientSossusvleiGuideTouristsDune: "/images/experiences/client-sossusvlei-guide-tourists-dune.webp",
    clientSandwichHarbourWomanArmsUp: "/images/experiences/client-sandwich-harbour-woman-arms-up.webp",
    clientSwakopmundJettySunset: "/images/experiences/client-swakopmund-jetty-sunset.webp",
    clientSpitzkoppeLodgeCoffeeDeck: "/images/experiences/client-spitzkoppe-lodge-coffee-deck.webp",
    clientSafariLodgeInterior: "/images/experiences/client-safari-lodge-interior.webp",
    clientLuxuryTentBathtubDesert: "/images/experiences/client-luxury-tent-bathtub-desert.webp",
    clientLuxuryTentBedView: "/images/experiences/client-luxury-tent-bed-view.webp",
    clientInfinityPoolMeditationDesert: "/images/experiences/client-infinity-pool-meditation-desert.webp",
    clientNamibDuneWomanSitting: "/images/experiences/client-namib-dune-woman-sitting.webp",
    clientEtoshaLodgeExteriorSunset: "/images/experiences/client-etosha-lodge-exterior-sunset.webp",
    clientPinkLakeWomenGroup: "/images/experiences/client-pink-lake-women-group.webp",
    clientDunesWomenGroupColourful: "/images/experiences/client-dunes-women-group-colourful.webp",
    clientCatamaranWomenGroupHarbour: "/images/experiences/client-catamaran-women-group-harbour.webp",
  },
  airports: {
    walvisBayExterior: "/images/airports/proavia-airport-walvis-bay-exterior.webp",
    airlinkPlane: "/images/airports/proavia-airport-airlink-plane.webp",
  },
  transfers: {
    luggageLoading: "/images/transfers/proavia-transfer-luggage-loading.webp",
    meetAndGreet: "/images/transfers/airport-meet-and-greet.webp",
    airportPickup: "/images/transfers/airport-pickup-minivan.webp",
    luggageTrunk: "/images/transfers/proavia-transfer-luggage-trunk-ready.webp",
    shuttleOperation: "/images/transfers/proavia-transfer-shuttle-operation.webp",
    vansParked: "/images/transfers/proavia-transfer-vans-parked.webp",
  },
} as const;
