export const IMAGES = {
  logo: "/images/proavia-logo-light.webp",
  logoDark: "/images/proavia-logo-dark.webp",
  logoPng: "/images/proavia-logo-light.png",
  logoDarkPng: "/images/proavia-logo-dark.png",
  icon: "/images/icon.webp",
  attaLogo: "/images/atta-logo.webp",
  nipdbLogo: "/images/nipdb-logo.webp",
  ntbLogo: "/images/ntb-logo.webp",
  destinations: {
    sandwichHarbourOceanView: "/images/destinations/destination-sandwich-harbour-ocean-view.webp",
    sandwichHarbourCoastalDunes: "/images/destinations/destination-sandwich-harbour-coastal-dunes.webp",
    sandwichHarbourSuvDrive: "/images/destinations/destination-sandwich-harbour-suv-drive.webp",
    sandwichHarbourDuneClimb: "/images/destinations/destination-sandwich-harbour-dune-climb.webp",
    sandwichHarbourSunsetPicnic: "/images/destinations/destination-sandwich-harbour-sunset-picnic.webp",
    walvisBaySaltShore: "/images/destinations/destination-walvis-bay-salt-shore.webp",
    walvisBaySaltPans: "/images/destinations/destination-walvis-bay-salt-pans-crystals.webp",
    walvisBayPinkLake: "/images/destinations/destination-walvis-bay-pink-lake.webp",
    namibDesertPinkSeating: "/images/destinations/destination-namib-desert-pink-seating.webp",
  },
  vehicles: {
    blackSuv: "/images/vehicles/vehicle-proavia-black-suv.webp",
    windhoekTransfer: "/images/vehicles/vehicle-windhoek-airport-transfer.webp",
    walvisBayShuttle: "/images/vehicles/vehicle-walvis-bay-airport-shuttle.webp",
    volkswagenSossusvlei: "/images/vehicles/fleet-volkswagen-in-sosslvei.webp",
    volkswagenVehicle: "/images/vehicles/fleet-volskwagen-vehicle.webp",
  },
  experiences: {
    safariElephant: "/images/experiences/proavia-tour-safari-elephant.webp",
    pinkLake: "/images/experiences/proavia-tour-pink-lake-experience.webp",
    marineCatamaran: "/images/experiences/proavia-tour-marine-catamaran.webp",
    desertSuv: "/images/experiences/proavia-tour-desert-suv.webp",
    safariGiraffe: "/images/experiences/proavia-tour-safari-giraffe.webp",
    wildlifeElephantZebras: "/images/experiences/proavia-tour-wildlife-elephant-zebras.webp",
    adventureParagliding: "/images/experiences/proavia-tour-adventure-paragliding.webp",
    desertHeadstand: "/images/experiences/proavia-tour-desert-headstand-fun.webp",
    duneTopFlag: "/images/experiences/experience-dune-top-namibia-flag.webp",
    sandboarding: "/images/experiences/experience-sandboarding-beach.webp",
    portCruiseNight: "/images/experiences/proavia-port-cruise-ship-night.webp",
    duneTracks: "/images/experiences/experience-4x4-dune-tracks.webp",
    pelicanBoat: "/images/experiences/experience-pelican-boat-tour.webp",
  },
  airports: {
    walvisBayExterior: "/images/airports/proavia-airport-walvis-bay-exterior.webp",
    airlinkPlane: "/images/airports/proavia-airport-airlink-plane.webp",
  },
  transfers: {
    luggageLoading: "/images/transfers/proavia-transfer-luggage-loading.webp",
    shuttleBoarding: "/images/transfers/proavia-transfer-shuttle-boarding.webp",
    passengersBoarding: "/images/transfers/proavia-transfer-passengers-boarding.webp",
    luggageTrunk: "/images/transfers/proavia-transfer-luggage-trunk-ready.webp",
    shuttleOperation: "/images/transfers/proavia-transfer-shuttle-operation.webp",
    vansParked: "/images/transfers/proavia-transfer-vans-parked.webp",
  },
} as const;
